---

- name: Add buster-backports repository into sources list for wireguard
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    update_cache: yes

- name: install wireguard
  become: yes
  apt:
    name: wireguard
 
 # set config files here:
 
 
 #keygen script stuff
- name: make keygen directory
  become: yes
  file:
    path: /root/.wireguard # change dir to whatever is standard
    state: directory
    mode: '077'

- name: generate keys if 'privatekey' does not exist
  become: yes
  shell: wg genkey | tee privatekey | wg pubkey > publickey  
  args:  
    chdir: /root/.wireguard
    creates: /root/.wireguard/privatekey

- name: enable ip forwarding for vpn server
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
# - name: install config
#   template:
#     src: wg0.conf.j2
#     dest: /etc/wireguard/wg0.conf
#     owner: root
#     group: root
#     mode: "0644"

#  # Not yet working
# - name: enable and start wireguard service
#   become: yes
#   systemd: 
#     name: wg-quick@wg0
#     enabled: yes
#     state: started

    
