---
# wireguard is not included in debian 10, but is in debian 11. buster-backports gives us access to debian 11 packages.
- name: Add buster-backports repository into sources list for wireguard
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    update_cache: yes

- name: install wireguard
  become: yes
  apt:
    name: wireguard

# enable the wireguard kernel module so we can enable logging for it.
- name: enable wireguard kernel module
  become: yes
  modprobe:
    name: wireguard
    state: present  

# runs every time, this is okay.
- name: enable wireguard logging
  become: yes
  shell: echo 'module wireguard +p' > /sys/kernel/debug/dynamic_debug/control

# forward packets from the network-facing interface to the WireGuard interface
- name: enable ip forwarding for vpn server
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

# generate config from vars
- name: load config
  become: yes
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0644"
  notify: "live config reload"

# enable debug log filtering
- name: transfer rsyslog wireguard conf
  ansible.builtin.copy:
    src: wireguard.conf
    dest: /etc/rsyslog.d/wireguard.conf
    owner: root
    group: root
  notify: restart rsyslog

  # enable debug log filtering
- name: transfer rsyslog wireguard conf
  ansible.builtin.copy:
    src: wireguard_debug.sh
    dest: /etc/rc.local
    owner: root
    group: root
    mode: "0755"

# manage the systemctl service
- name: enable and start wireguard service
  become: yes
  service: 
    name: wg-quick@wg0
    enabled: yes
    state: started
